// esbuild driver for the play.conssswars.com browser bridge.
//
// Bundles bridge/src/index.js (+ @mysten/sui, @mysten/walrus,
// @mysten/wallet-standard) into ../public/dist/dapp-kit-bridge.bundle.js,
// which the Godot HTML5 shell (public/index.html) loads.
//
// Unlike the app-repo build, config is split: bridge/config.public.js holds
// the public IDs/URLs and is committed; the secret Tatum API key is injected
// here from the TATUM_API_KEY env var via the `__TATUM_API_KEY__` define.
// No config.local.js, so nothing secret ever lands in git. If TATUM_API_KEY
// is unset the key is empty and the bridge falls back to the public RPC.

import { build, context } from 'esbuild';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const bridgeRoot = resolve(here, '..');
const outfile = resolve(bridgeRoot, '../public/dist/dapp-kit-bridge.bundle.js');

const tatumKey = process.env.TATUM_API_KEY ?? '';
if (!tatumKey) {
  console.warn(
    '[build] TATUM_API_KEY not set — bundling with an empty key.\n' +
      '        The game still works via the public RPC fallback; set the\n' +
      '        TATUM_API_KEY env var (CF Pages secret) for the Tatum gateway.',
  );
}

const options = {
  entryPoints: [resolve(bridgeRoot, 'src/index.js')],
  bundle: true,
  format: 'esm',
  target: ['es2022'],
  platform: 'browser',
  outfile,
  sourcemap: 'linked',
  minify: true,
  treeShaking: true,
  define: {
    '__TATUM_API_KEY__': JSON.stringify(tatumKey),
    'process.env.NODE_ENV': '"production"',
    global: 'globalThis',
  },
  loader: { '.wasm': 'file' },
  banner: {
    js: '// ConSSS Wars play bridge — generated by bridge/scripts/build.mjs. DO NOT EDIT BY HAND.',
  },
  logLevel: 'info',
};

if (process.argv.includes('--watch')) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('[build] watching bridge/src for changes…');
} else {
  await build(options);
  console.log('[build] wrote public/dist/dapp-kit-bridge.bundle.js');
}
