// esbuild driver for the play.conssswars.com browser bridge.
//
// Bundles bridge/src/index.js (+ @mysten/sui, @mysten/walrus,
// @mysten/wallet-standard) into ../public/dist/dapp-kit-bridge.bundle.js,
// which the Godot HTML5 shell (public/index.html) loads.
//
// No secrets are baked in: Sui RPC goes through the same-origin /rpc Pages
// Function, which holds the Tatum API key server-side. config.public.js has
// only public IDs/URLs, so nothing secret ever reaches the bundle or git.

import { build, context } from 'esbuild';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const bridgeRoot = resolve(here, '..');
const outfile = resolve(bridgeRoot, '../public/dist/dapp-kit-bridge.bundle.js');

const options = {
  entryPoints: [resolve(bridgeRoot, 'src/index.js')],
  bundle: true,
  format: 'esm',
  target: ['es2022'],
  platform: 'browser',
  outfile,
  sourcemap: 'linked',
  minify: true,
  treeShaking: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    global: 'globalThis',
  },
  loader: { '.wasm': 'file' },
  banner: {
    js: '// ConSSS Wars play bridge — generated by bridge/scripts/build.mjs. DO NOT EDIT BY HAND.',
  },
  logLevel: 'info',
};

if (process.argv.includes('--watch')) {
  const ctx = await context(options);
  await ctx.watch();
  console.log('[build] watching bridge/src for changes…');
} else {
  await build(options);
  console.log('[build] wrote public/dist/dapp-kit-bridge.bundle.js');
}
